### ISSUE TITLE
avconv no Arch

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/tesseract-mapillary#2]
Ref.: Sonerezh/sonerezh#3 + wargio/Twitch-Streamer-Linux#2

Estou procurando alternativa. Talvez o programa esteja como outro comando.

**Comment by alexandre-mbm** [comment]
avconv é um _fork_ do ffmpeg. Testarei se dá pra substituir um pelo outro.

Um pacote de [Libav](https://libav.org/), que [haveria](https://en.wikipedia.org/wiki/Libav) no AUR, forneceria o comando [avconv](http://packages.ubuntu.com/precise/amd64/libav-tools/filelist). Mas eu prefiro usar o ffmpeg e com isso as dependências ficarem mais generalistas.

**Comment by alexandre-mbm** [comment]
OK. O seguinte comando foi possível:

``` sh
ffmpeg -i arquivo.mp4 -qscale:v 2 -r 1/1 "1/%03d.jpg"
```

**Comment by nighto** [comment]
Sim, tanto faz. Coloquei o `avconv` porque foi o que usei aqui na VM do Ubuntu, mas pode ser o `ffmpeg` sem problemas.
